[GLOBAL]
pants_version = '2.24.0a0'

backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.autoflake',
  'pants.backend.build_files.fmt.black',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.docformatter',
  'pants.backend.tools.taplo',
  "pants.backend.experimental.python",
]

pants_ignore.add = ['!_test_scripts/', '!_dev_scripts/']

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ['/', 'src/', 'tests/']

[python]
interpreter_constraints = ['==3.12.*']

[pytest]
args = ['-vv', '--no-header']

[coverage-py]
interpreter_constraints = ['>=3.8']
report = ['html', 'console']

[black]
args = ['--line-length=90', '--skip-string-normalization']
interpreter_constraints = ['>=3.8']

[isort]
args = ['--profile=black', '--line-length=90']
interpreter_constraints = ['>=3.8']

[docformatter]
args = ['--wrap-summaries=90', '--wrap-descriptions=90']
interpreter_constraints = ['>=3.8']

[autoflake]
interpreter_constraints = ['>=3.8']
