[GLOBAL]
pants_version = '2.21.0'

backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.autoflake',
  'pants.backend.build_files.fmt.black',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.docformatter',
  'pants.backend.tools.taplo',
  "pants.backend.experimental.python",
]

pants_ignore.add = ['!_test_scripts/']

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ['/', 'src/', 'tests/']

[python]
interpreter_constraints = ['==3.11.*']

[pytest]
args = ['-vv', '--no-header']

[coverage-py]
interpreter_constraints = ['>=3.8']
report = ['html', 'console']
filter = [
  'vonage/src',
  'vonage_network/src',
  'http_client/src',
  'application/src',
  'jwt/src',
  'messages/src',
  'network_auth/src',
  'network_sim_swap/src',
  'number_insight/src',
  'number_insight_v2/src',
  'sms/src',
  'users/src',
  'utils/src',
  'testutils',
  'verify/src',
  'verify_v2/src',
  'voice/src',
  'vonage_utils/src',
]

[black]
args = ['--line-length=90', '--skip-string-normalization']

[isort]
args = ['--profile=black', '--line-length=90']

[docformatter]
args = ['--wrap-summaries=100', '--wrap-descriptions=100']
